/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`banknote_get_banknote_by_cert_no`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BanknoteGetBanknoteByCertNoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`banknote_get_banknote_by_grade`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BanknoteGetBanknoteByGradeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`banknote_get_banknote_images_by_cert_no`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BanknoteGetBanknoteImagesByCertNoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`coin_detail_get_aprby_barcode`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CoinDetailGetAprbyBarcodeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`coin_detail_get_aprby_cert_no`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CoinDetailGetAprbyCertNoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`coin_detail_get_aprby_grade`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CoinDetailGetAprbyGradeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`coin_detail_get_coin_facts_by_barcode`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CoinDetailGetCoinFactsByBarcodeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`coin_detail_get_coin_facts_by_cert_no`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CoinDetailGetCoinFactsByCertNoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`coin_detail_get_coin_facts_by_grade`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CoinDetailGetCoinFactsByGradeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`coin_detail_get_images_by_cert_no`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CoinDetailGetImagesByCertNoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`order_get_orders_by_date_range`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrderGetOrdersByDateRangeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`order_get_orders_by_submission_no`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrderGetOrdersBySubmissionNoError {
    UnknownValue(serde_json::Value),
}


pub async fn banknote_get_banknote_by_cert_no(configuration: &configuration::Configuration, cert_no: &str, language_code: Option<&str>) -> Result<models::BanknoteModel, Error<BanknoteGetBanknoteByCertNoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_cert_no = cert_no;
    let p_query_language_code = language_code;

    let uri_str = format!("{}/banknotedetail/GetBanknoteByCertNo", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("certNo", &p_query_cert_no.to_string())]);
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("languageCode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BanknoteModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BanknoteModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BanknoteGetBanknoteByCertNoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn banknote_get_banknote_by_grade(configuration: &configuration::Configuration, pcgs_no: &str, grade_no: i32) -> Result<models::BanknotesModel, Error<BanknoteGetBanknoteByGradeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_pcgs_no = pcgs_no;
    let p_query_grade_no = grade_no;

    let uri_str = format!("{}/banknotedetail/GetBanknoteByGrade", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("pcgsNo", &p_query_pcgs_no.to_string())]);
    req_builder = req_builder.query(&[("gradeNo", &p_query_grade_no.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BanknotesModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BanknotesModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BanknoteGetBanknoteByGradeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn banknote_get_banknote_images_by_cert_no(configuration: &configuration::Configuration, cert_no: &str) -> Result<models::ImageModel, Error<BanknoteGetBanknoteImagesByCertNoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_cert_no = cert_no;

    let uri_str = format!("{}/banknotedetail/GetBanknoteImagesByCertNo", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("certNo", &p_query_cert_no.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ImageModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ImageModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BanknoteGetBanknoteImagesByCertNoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn coin_detail_get_aprby_barcode(configuration: &configuration::Configuration, barcode: &str, grading_service: &str, start_date: Option<String>, end_date: Option<String>) -> Result<models::CoinFactsModel, Error<CoinDetailGetAprbyBarcodeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_barcode = barcode;
    let p_query_grading_service = grading_service;
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;

    let uri_str = format!("{}/coindetail/GetAPRByBarcode", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("barcode", &p_query_barcode.to_string())]);
    req_builder = req_builder.query(&[("gradingService", &p_query_grading_service.to_string())]);
    if let Some(ref param_value) = p_query_start_date {
        req_builder = req_builder.query(&[("StartDate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_date {
        req_builder = req_builder.query(&[("EndDate", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CoinFactsModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CoinFactsModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CoinDetailGetAprbyBarcodeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn coin_detail_get_aprby_cert_no(configuration: &configuration::Configuration, cert_no: &str) -> Result<models::AuctionModel, Error<CoinDetailGetAprbyCertNoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_cert_no = cert_no;

    let uri_str = format!("{}/coindetail/GetAPRByCertNo/{CertNo}", configuration.base_path, CertNo=crate::apis::urlencode(p_path_cert_no));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuctionModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuctionModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CoinDetailGetAprbyCertNoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn coin_detail_get_aprby_grade(configuration: &configuration::Configuration, pcgsno: &str, grade_no: i32, plus_grade: bool, start_date: Option<String>, end_date: Option<String>, number_of_records: Option<i32>) -> Result<models::AuctionListModel, Error<CoinDetailGetAprbyGradeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_pcgsno = pcgsno;
    let p_query_grade_no = grade_no;
    let p_query_plus_grade = plus_grade;
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;
    let p_query_number_of_records = number_of_records;

    let uri_str = format!("{}/coindetail/GetAPRByGrade", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("PCGSNo", &p_query_pcgsno.to_string())]);
    req_builder = req_builder.query(&[("GradeNo", &p_query_grade_no.to_string())]);
    req_builder = req_builder.query(&[("PlusGrade", &p_query_plus_grade.to_string())]);
    if let Some(ref param_value) = p_query_start_date {
        req_builder = req_builder.query(&[("StartDate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_date {
        req_builder = req_builder.query(&[("EndDate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_number_of_records {
        req_builder = req_builder.query(&[("NumberOfRecords", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuctionListModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuctionListModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CoinDetailGetAprbyGradeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn coin_detail_get_coin_facts_by_barcode(configuration: &configuration::Configuration, barcode: &str, grading_service: &str) -> Result<models::CoinFactsByBarcodeModel, Error<CoinDetailGetCoinFactsByBarcodeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_barcode = barcode;
    let p_query_grading_service = grading_service;

    let uri_str = format!("{}/coindetail/GetCoinFactsByBarcode", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("barcode", &p_query_barcode.to_string())]);
    req_builder = req_builder.query(&[("gradingService", &p_query_grading_service.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CoinFactsByBarcodeModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CoinFactsByBarcodeModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CoinDetailGetCoinFactsByBarcodeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn coin_detail_get_coin_facts_by_cert_no(configuration: &configuration::Configuration, cert_no: &str, retrieve_all_data: Option<bool>) -> Result<models::CoinFactsModel, Error<CoinDetailGetCoinFactsByCertNoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_cert_no = cert_no;
    let p_query_retrieve_all_data = retrieve_all_data;

    let uri_str = format!("{}/coindetail/GetCoinFactsByCertNo/{certNo}", configuration.base_path, certNo=crate::apis::urlencode(p_path_cert_no));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_retrieve_all_data {
        req_builder = req_builder.query(&[("retrieveAllData", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CoinFactsModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CoinFactsModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CoinDetailGetCoinFactsByCertNoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn coin_detail_get_coin_facts_by_grade(configuration: &configuration::Configuration, pcgsno: &str, grade_no: i32, plus_grade: bool) -> Result<models::CoinFactsByGradeModel, Error<CoinDetailGetCoinFactsByGradeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_pcgsno = pcgsno;
    let p_query_grade_no = grade_no;
    let p_query_plus_grade = plus_grade;

    let uri_str = format!("{}/coindetail/GetCoinFactsByGrade", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("PCGSNo", &p_query_pcgsno.to_string())]);
    req_builder = req_builder.query(&[("GradeNo", &p_query_grade_no.to_string())]);
    req_builder = req_builder.query(&[("PlusGrade", &p_query_plus_grade.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CoinFactsByGradeModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CoinFactsByGradeModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CoinDetailGetCoinFactsByGradeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn coin_detail_get_images_by_cert_no(configuration: &configuration::Configuration, cert_no: &str) -> Result<models::ImageModel, Error<CoinDetailGetImagesByCertNoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_cert_no = cert_no;

    let uri_str = format!("{}/coindetail/GetImagesByCertNo", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("certNo", &p_query_cert_no.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ImageModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ImageModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CoinDetailGetImagesByCertNoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn order_get_orders_by_date_range(configuration: &configuration::Configuration, start_date: &str, end_date: &str, page_no: Option<i32>, page_size: Option<i32>) -> Result<models::OrderModel, Error<OrderGetOrdersByDateRangeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;
    let p_query_page_no = page_no;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/orderdetail/GetOrdersByDateRange", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("startDate", &p_query_start_date.to_string())]);
    req_builder = req_builder.query(&[("endDate", &p_query_end_date.to_string())]);
    if let Some(ref param_value) = p_query_page_no {
        req_builder = req_builder.query(&[("pageNo", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrderModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrderModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrderGetOrdersByDateRangeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn order_get_orders_by_submission_no(configuration: &configuration::Configuration, submission_no: &str) -> Result<models::OrderModel, Error<OrderGetOrdersBySubmissionNoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_submission_no = submission_no;

    let uri_str = format!("{}/orderdetail/GetOrdersBySubmissionNo", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("submissionNo", &p_query_submission_no.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrderModel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrderModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrderGetOrdersBySubmissionNoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

