/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuctionListModel {
    #[serde(rename = "PCGSNo", skip_serializing_if = "Option::is_none")]
    pub pcgsno: Option<String>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Year", skip_serializing_if = "Option::is_none")]
    pub year: Option<String>,
    #[serde(rename = "Denomination", skip_serializing_if = "Option::is_none")]
    pub denomination: Option<String>,
    #[serde(rename = "Auctions", skip_serializing_if = "Option::is_none")]
    pub auctions: Option<Vec<models::AuctionItem>>,
    /// 
    #[serde(rename = "IsValidRequest", skip_serializing_if = "Option::is_none")]
    pub is_valid_request: Option<bool>,
    /// 
    #[serde(rename = "ServerMessage", skip_serializing_if = "Option::is_none")]
    pub server_message: Option<String>,
}

impl AuctionListModel {
    pub fn new() -> AuctionListModel {
        AuctionListModel {
            pcgsno: None,
            name: None,
            year: None,
            denomination: None,
            auctions: None,
            is_valid_request: None,
            server_message: None,
        }
    }
}

