/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuctionItem {
    #[serde(rename = "Service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
    #[serde(rename = "Date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "Auctioneer", skip_serializing_if = "Option::is_none")]
    pub auctioneer: Option<String>,
    #[serde(rename = "LotNo", skip_serializing_if = "Option::is_none")]
    pub lot_no: Option<i32>,
    #[serde(rename = "LotNumV2", skip_serializing_if = "Option::is_none")]
    pub lot_num_v2: Option<String>,
    #[serde(rename = "SaleName", skip_serializing_if = "Option::is_none")]
    pub sale_name: Option<String>,
    #[serde(rename = "CertNo", skip_serializing_if = "Option::is_none")]
    pub cert_no: Option<String>,
    #[serde(rename = "Price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    #[serde(rename = "IsCAC", skip_serializing_if = "Option::is_none")]
    pub is_cac: Option<bool>,
    #[serde(rename = "AuctionLotUrl", skip_serializing_if = "Option::is_none")]
    pub auction_lot_url: Option<String>,
}

impl AuctionItem {
    pub fn new() -> AuctionItem {
        AuctionItem {
            service: None,
            date: None,
            auctioneer: None,
            lot_no: None,
            lot_num_v2: None,
            sale_name: None,
            cert_no: None,
            price: None,
            is_cac: None,
            auction_lot_url: None,
        }
    }
}

