/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Banknote : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Banknote {
    /// 
    #[serde(rename = "PCGSNo", skip_serializing_if = "Option::is_none")]
    pub pcgsno: Option<String>,
    /// 
    #[serde(rename = "CertNo", skip_serializing_if = "Option::is_none")]
    pub cert_no: Option<String>,
    /// 
    #[serde(rename = "Year", skip_serializing_if = "Option::is_none")]
    pub year: Option<String>,
    /// 
    #[serde(rename = "Denomination", skip_serializing_if = "Option::is_none")]
    pub denomination: Option<String>,
    /// 
    #[serde(rename = "Region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// 
    #[serde(rename = "Grade", skip_serializing_if = "Option::is_none")]
    pub grade: Option<String>,
    /// 
    #[serde(rename = "Details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// 
    #[serde(rename = "Population", skip_serializing_if = "Option::is_none")]
    pub population: Option<i32>,
    /// 
    #[serde(rename = "PopHigher", skip_serializing_if = "Option::is_none")]
    pub pop_higher: Option<i32>,
    /// 
    #[serde(rename = "SerialNo", skip_serializing_if = "Option::is_none")]
    pub serial_no: Option<String>,
    /// 
    #[serde(rename = "Height", skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
    /// 
    #[serde(rename = "Width", skip_serializing_if = "Option::is_none")]
    pub width: Option<String>,
    /// 
    #[serde(rename = "Images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::CertImage>>,
    /// 
    #[serde(rename = "CatalogNo1", skip_serializing_if = "Option::is_none")]
    pub catalog_no1: Option<String>,
    /// 
    #[serde(rename = "CatalogNo2", skip_serializing_if = "Option::is_none")]
    pub catalog_no2: Option<String>,
    /// 
    #[serde(rename = "Catalog1LongDesc", skip_serializing_if = "Option::is_none")]
    pub catalog1_long_desc: Option<String>,
    /// 
    #[serde(rename = "Catalog2LongDesc", skip_serializing_if = "Option::is_none")]
    pub catalog2_long_desc: Option<String>,
    /// 
    #[serde(rename = "Catalog1ShortDesc", skip_serializing_if = "Option::is_none")]
    pub catalog1_short_desc: Option<String>,
    /// 
    #[serde(rename = "Catalog2ShortDesc", skip_serializing_if = "Option::is_none")]
    pub catalog2_short_desc: Option<String>,
    /// 
    #[serde(rename = "Signers", skip_serializing_if = "Option::is_none")]
    pub signers: Option<String>,
    /// 
    #[serde(rename = "Qualifiers", skip_serializing_if = "Option::is_none")]
    pub qualifiers: Option<String>,
    /// 
    #[serde(rename = "PlateNo", skip_serializing_if = "Option::is_none")]
    pub plate_no: Option<String>,
    /// 
    #[serde(rename = "ValueViewLink", skip_serializing_if = "Option::is_none")]
    pub value_view_link: Option<String>,
    /// 
    #[serde(rename = "HasObverseImage", skip_serializing_if = "Option::is_none")]
    pub has_obverse_image: Option<bool>,
    /// 
    #[serde(rename = "HasReverseImage", skip_serializing_if = "Option::is_none")]
    pub has_reverse_image: Option<bool>,
    /// 
    #[serde(rename = "ImageReady", skip_serializing_if = "Option::is_none")]
    pub image_ready: Option<bool>,
}

impl Banknote {
    /// 
    pub fn new() -> Banknote {
        Banknote {
            pcgsno: None,
            cert_no: None,
            year: None,
            denomination: None,
            region: None,
            grade: None,
            details: None,
            population: None,
            pop_higher: None,
            serial_no: None,
            height: None,
            width: None,
            images: None,
            catalog_no1: None,
            catalog_no2: None,
            catalog1_long_desc: None,
            catalog2_long_desc: None,
            catalog1_short_desc: None,
            catalog2_short_desc: None,
            signers: None,
            qualifiers: None,
            plate_no: None,
            value_view_link: None,
            has_obverse_image: None,
            has_reverse_image: None,
            image_ready: None,
        }
    }
}

