/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BanknotesModel : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BanknotesModel {
    /// 
    #[serde(rename = "Banknotes", skip_serializing_if = "Option::is_none")]
    pub banknotes: Option<Vec<models::Banknote>>,
    /// 
    #[serde(rename = "IsValidRequest", skip_serializing_if = "Option::is_none")]
    pub is_valid_request: Option<bool>,
    /// 
    #[serde(rename = "ServerMessage", skip_serializing_if = "Option::is_none")]
    pub server_message: Option<String>,
}

impl BanknotesModel {
    /// 
    pub fn new() -> BanknotesModel {
        BanknotesModel {
            banknotes: None,
            is_valid_request: None,
            server_message: None,
        }
    }
}

