/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CertImage : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertImage {
    /// 
    #[serde(rename = "Label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// 
    #[serde(rename = "ThumbnailUrl", skip_serializing_if = "Option::is_none")]
    pub thumbnail_url: Option<String>,
    /// 
    #[serde(rename = "PopupUrl", skip_serializing_if = "Option::is_none")]
    pub popup_url: Option<String>,
    /// 
    #[serde(rename = "Width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    /// 
    #[serde(rename = "Height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    /// 
    #[serde(rename = "ImageDescription", skip_serializing_if = "Option::is_none")]
    pub image_description: Option<String>,
}

impl CertImage {
    /// 
    pub fn new() -> CertImage {
        CertImage {
            label: None,
            thumbnail_url: None,
            popup_url: None,
            width: None,
            height: None,
            image_description: None,
        }
    }
}

