/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CoinFactsImage : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoinFactsImage {
    /// 
    #[serde(rename = "Thumbnail", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<String>,
    /// 
    #[serde(rename = "Fullsize", skip_serializing_if = "Option::is_none")]
    pub fullsize: Option<String>,
}

impl CoinFactsImage {
    /// 
    pub fn new() -> CoinFactsImage {
        CoinFactsImage {
            thumbnail: None,
            fullsize: None,
        }
    }
}

