/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CoinFactsModel : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoinFactsModel {
    /// 
    #[serde(rename = "PCGSNo", skip_serializing_if = "Option::is_none")]
    pub pcgsno: Option<String>,
    /// 
    #[serde(rename = "CertNo", skip_serializing_if = "Option::is_none")]
    pub cert_no: Option<String>,
    /// 
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 
    #[serde(rename = "Year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
    /// 
    #[serde(rename = "Denomination", skip_serializing_if = "Option::is_none")]
    pub denomination: Option<String>,
    /// 
    #[serde(rename = "Mintage", skip_serializing_if = "Option::is_none")]
    pub mintage: Option<String>,
    /// 
    #[serde(rename = "MintMark", skip_serializing_if = "Option::is_none")]
    pub mint_mark: Option<String>,
    /// 
    #[serde(rename = "MintLocation", skip_serializing_if = "Option::is_none")]
    pub mint_location: Option<String>,
    /// 
    #[serde(rename = "MetalContent", skip_serializing_if = "Option::is_none")]
    pub metal_content: Option<String>,
    /// 
    #[serde(rename = "Diameter", skip_serializing_if = "Option::is_none")]
    pub diameter: Option<f64>,
    /// 
    #[serde(rename = "Edge", skip_serializing_if = "Option::is_none")]
    pub edge: Option<String>,
    /// 
    #[serde(rename = "Weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    /// 
    #[serde(rename = "Country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// 
    #[serde(rename = "Grade", skip_serializing_if = "Option::is_none")]
    pub grade: Option<String>,
    /// 
    #[serde(rename = "Designation", skip_serializing_if = "Option::is_none")]
    pub designation: Option<String>,
    /// 
    #[serde(rename = "PriceGuideValue", skip_serializing_if = "Option::is_none")]
    pub price_guide_value: Option<f64>,
    /// 
    #[serde(rename = "Population", skip_serializing_if = "Option::is_none")]
    pub population: Option<i32>,
    /// 
    #[serde(rename = "PopHigher", skip_serializing_if = "Option::is_none")]
    pub pop_higher: Option<i32>,
    /// 
    #[serde(rename = "CoinFactsLink", skip_serializing_if = "Option::is_none")]
    pub coin_facts_link: Option<String>,
    /// 
    #[serde(rename = "Designer", skip_serializing_if = "Option::is_none")]
    pub designer: Option<String>,
    /// 
    #[serde(rename = "Images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::CoinFactsImage>>,
    /// 
    #[serde(rename = "CoinFactsNotes", skip_serializing_if = "Option::is_none")]
    pub coin_facts_notes: Option<String>,
    /// 
    #[serde(rename = "MajorVariety", skip_serializing_if = "Option::is_none")]
    pub major_variety: Option<String>,
    /// 
    #[serde(rename = "MinorVariety", skip_serializing_if = "Option::is_none")]
    pub minor_variety: Option<String>,
    /// 
    #[serde(rename = "DieVariety", skip_serializing_if = "Option::is_none")]
    pub die_variety: Option<String>,
    /// 
    #[serde(rename = "AuctionList", skip_serializing_if = "Option::is_none")]
    pub auction_list: Option<Vec<models::AuctionItem>>,
    /// 
    #[serde(rename = "SeriesName", skip_serializing_if = "Option::is_none")]
    pub series_name: Option<String>,
    /// 
    #[serde(rename = "Category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// 
    #[serde(rename = "HasTrueViewImage", skip_serializing_if = "Option::is_none")]
    pub has_true_view_image: Option<bool>,
    /// 
    #[serde(rename = "ImageReady", skip_serializing_if = "Option::is_none")]
    pub image_ready: Option<bool>,
    /// 
    #[serde(rename = "IsNFCSecure", skip_serializing_if = "Option::is_none")]
    pub is_nfc_secure: Option<bool>,
    /// 
    #[serde(rename = "IsValidRequest", skip_serializing_if = "Option::is_none")]
    pub is_valid_request: Option<bool>,
    /// 
    #[serde(rename = "ServerMessage", skip_serializing_if = "Option::is_none")]
    pub server_message: Option<String>,
}

impl CoinFactsModel {
    /// 
    pub fn new() -> CoinFactsModel {
        CoinFactsModel {
            pcgsno: None,
            cert_no: None,
            name: None,
            year: None,
            denomination: None,
            mintage: None,
            mint_mark: None,
            mint_location: None,
            metal_content: None,
            diameter: None,
            edge: None,
            weight: None,
            country: None,
            grade: None,
            designation: None,
            price_guide_value: None,
            population: None,
            pop_higher: None,
            coin_facts_link: None,
            designer: None,
            images: None,
            coin_facts_notes: None,
            major_variety: None,
            minor_variety: None,
            die_variety: None,
            auction_list: None,
            series_name: None,
            category: None,
            has_true_view_image: None,
            image_ready: None,
            is_nfc_secure: None,
            is_valid_request: None,
            server_message: None,
        }
    }
}

