/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GradingOrderLineSummary : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GradingOrderLineSummary {
    /// 
    #[serde(rename = "LineNo", skip_serializing_if = "Option::is_none")]
    pub line_no: Option<i32>,
    /// 
    #[serde(rename = "ItemNo", skip_serializing_if = "Option::is_none")]
    pub item_no: Option<i32>,
    /// 
    #[serde(rename = "CertNo", skip_serializing_if = "Option::is_none")]
    pub cert_no: Option<String>,
    /// 
    #[serde(rename = "PCGSNo", skip_serializing_if = "Option::is_none")]
    pub pcgsno: Option<String>,
    /// 
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// 
    #[serde(rename = "DisplayGrade", skip_serializing_if = "Option::is_none")]
    pub display_grade: Option<String>,
    /// 
    #[serde(rename = "Country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// 
    #[serde(rename = "Images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<String>>,
}

impl GradingOrderLineSummary {
    /// 
    pub fn new() -> GradingOrderLineSummary {
        GradingOrderLineSummary {
            line_no: None,
            item_no: None,
            cert_no: None,
            pcgsno: None,
            description: None,
            display_grade: None,
            country: None,
            images: None,
        }
    }
}

