/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageModel {
    #[serde(rename = "CertNo", skip_serializing_if = "Option::is_none")]
    pub cert_no: Option<String>,
    #[serde(rename = "Images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::ImageDetail>>,
    /// 
    #[serde(rename = "HasObverseImage", skip_serializing_if = "Option::is_none")]
    pub has_obverse_image: Option<bool>,
    /// 
    #[serde(rename = "HasReverseImage", skip_serializing_if = "Option::is_none")]
    pub has_reverse_image: Option<bool>,
    /// 
    #[serde(rename = "HasTrueViewImage", skip_serializing_if = "Option::is_none")]
    pub has_true_view_image: Option<bool>,
    /// 
    #[serde(rename = "ImageReady", skip_serializing_if = "Option::is_none")]
    pub image_ready: Option<bool>,
    /// 
    #[serde(rename = "IsValidRequest", skip_serializing_if = "Option::is_none")]
    pub is_valid_request: Option<bool>,
    /// 
    #[serde(rename = "ServerMessage", skip_serializing_if = "Option::is_none")]
    pub server_message: Option<String>,
}

impl ImageModel {
    pub fn new() -> ImageModel {
        ImageModel {
            cert_no: None,
            images: None,
            has_obverse_image: None,
            has_reverse_image: None,
            has_true_view_image: None,
            image_ready: None,
            is_valid_request: None,
            server_message: None,
        }
    }
}

