/*
 * PCGS Public API
 *
 * This is the documentation for the PCGS public API. For security, it your public api token to authenticate. To test the calls using this page you need to fill the textbox marked 'token' with your token generated <a href=https://www.pcgs.com/publicapi/documentation>here</a>.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderDetailModel : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderDetailModel {
    /// 
    #[serde(rename = "SubmissionNo", skip_serializing_if = "Option::is_none")]
    pub submission_no: Option<String>,
    /// 
    #[serde(rename = "OrderNo", skip_serializing_if = "Option::is_none")]
    pub order_no: Option<String>,
    /// 
    #[serde(rename = "CustomerNo", skip_serializing_if = "Option::is_none")]
    pub customer_no: Option<String>,
    /// 
    #[serde(rename = "ItemCount", skip_serializing_if = "Option::is_none")]
    pub item_count: Option<i32>,
    /// 
    #[serde(rename = "Service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
    /// 
    #[serde(rename = "OrderStatus", skip_serializing_if = "Option::is_none")]
    pub order_status: Option<String>,
    /// 
    #[serde(rename = "DateReceived", skip_serializing_if = "Option::is_none")]
    pub date_received: Option<String>,
    /// 
    #[serde(rename = "DateShipped", skip_serializing_if = "Option::is_none")]
    pub date_shipped: Option<String>,
    /// 
    #[serde(rename = "Courier", skip_serializing_if = "Option::is_none")]
    pub courier: Option<String>,
    /// 
    #[serde(rename = "TrackingNo", skip_serializing_if = "Option::is_none")]
    pub tracking_no: Option<String>,
    /// 
    #[serde(rename = "TrackingUrl", skip_serializing_if = "Option::is_none")]
    pub tracking_url: Option<String>,
    /// 
    #[serde(rename = "IsCancelled", skip_serializing_if = "Option::is_none")]
    pub is_cancelled: Option<bool>,
    /// 
    #[serde(rename = "ImageInProcess", skip_serializing_if = "Option::is_none")]
    pub image_in_process: Option<bool>,
    /// 
    #[serde(rename = "ImageReady", skip_serializing_if = "Option::is_none")]
    pub image_ready: Option<bool>,
    /// 
    #[serde(rename = "GradeReady", skip_serializing_if = "Option::is_none")]
    pub grade_ready: Option<bool>,
    /// 
    #[serde(rename = "OrderLines", skip_serializing_if = "Option::is_none")]
    pub order_lines: Option<Vec<models::GradingOrderLineSummary>>,
}

impl OrderDetailModel {
    /// 
    pub fn new() -> OrderDetailModel {
        OrderDetailModel {
            submission_no: None,
            order_no: None,
            customer_no: None,
            item_count: None,
            service: None,
            order_status: None,
            date_received: None,
            date_shipped: None,
            courier: None,
            tracking_no: None,
            tracking_url: None,
            is_cancelled: None,
            image_in_process: None,
            image_ready: None,
            grade_ready: None,
            order_lines: None,
        }
    }
}

